// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_pack_icon_index from "./routes/[pack]/[icon]/index.tsx";
import * as $_pack_icon_preact from "./routes/[pack]/[icon]/preact.tsx";
import * as $_pack_icon_qwik from "./routes/[pack]/[icon]/qwik.tsx";
import * as $_pack_icon_react from "./routes/[pack]/[icon]/react.tsx";
import * as $_pack_icon_solid_js from "./routes/[pack]/[icon]/solid-js.tsx";
import * as $_pack_icon_svg from "./routes/[pack]/[icon]/svg.tsx";
import * as $_pack_icon_vue from "./routes/[pack]/[icon]/vue.tsx";
import * as $_pack_index from "./routes/[pack]/index.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $Neon from "./islands/Neon.tsx";
import * as $Typing from "./islands/Typing.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[pack]/[icon]/index.tsx": $_pack_icon_index,
    "./routes/[pack]/[icon]/preact.tsx": $_pack_icon_preact,
    "./routes/[pack]/[icon]/qwik.tsx": $_pack_icon_qwik,
    "./routes/[pack]/[icon]/react.tsx": $_pack_icon_react,
    "./routes/[pack]/[icon]/solid-js.tsx": $_pack_icon_solid_js,
    "./routes/[pack]/[icon]/svg.tsx": $_pack_icon_svg,
    "./routes/[pack]/[icon]/vue.tsx": $_pack_icon_vue,
    "./routes/[pack]/index.tsx": $_pack_index,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Neon.tsx": $Neon,
    "./islands/Typing.tsx": $Typing,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
